-- Migration: Add invoice number fields to finance_schedules
-- Date: 2025-12-02
-- Description: Adds internal_invoice_number (auto-generated) and external_invoice_number (reference from other companies)

-- Add internal invoice number (auto-generated by system)
ALTER TABLE finance_schedules
ADD COLUMN IF NOT EXISTS internal_invoice_number VARCHAR(100) UNIQUE;

-- Add external invoice number (reference from other company)
ALTER TABLE finance_schedules
ADD COLUMN IF NOT EXISTS external_invoice_number VARCHAR(100);

-- Add comment to columns
COMMENT ON COLUMN finance_schedules.internal_invoice_number IS 'Auto-generated internal invoice number';
COMMENT ON COLUMN finance_schedules.external_invoice_number IS 'External invoice reference number from other companies';
